# Generated by Django 4.0 on 2021-12-21 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('date', models.IntegerField()),
                ('month', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='subtitle',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
