# Generated by Django 4.0 on 2021-12-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_newposts_alter_testimonials_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSidebar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=50)),
            ],
        ),
    ]
