# Generated by Django 4.0 on 2021-12-22 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_newssidebar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newssidebar',
            name='img',
        ),
    ]
