# Generated by Django 4.0 on 2022-01-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='url',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
