# Generated by Django 4.0 on 2022-01-23 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_destination_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='url',
        ),
    ]
