# Generated by Django 4.0 on 2022-01-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_remove_destination_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='post_url',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
