# Generated by Django 4.0 on 2022-01-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_profile_bio_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='City',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='State',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='Street',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='Zip',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
