# Generated by Django 4.0 on 2022-01-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_profile_city_profile_state_profile_street_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='About',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
