# Generated by Django 4.0 on 2022-01-05 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_profile_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='About',
            new_name='Fullname',
        ),
    ]
