# Generated by Django 4.0 on 2022-01-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_remove_profile_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Zip',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
